// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTL;

#nullable disable

namespace QLTL.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20240601022505_QLTL")]
    partial class QLTL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTL.Models.CHAMCONG", b =>
                {
                    b.Property<long>("MACC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MACC"));

                    b.Property<long>("MANV")
                        .HasColumnType("bigint");

                    b.Property<int>("NAM")
                        .HasColumnType("int");

                    b.Property<int>("NGAYCONG")
                        .HasColumnType("int");

                    b.Property<int>("NGHIHL")
                        .HasColumnType("int");

                    b.Property<int>("THANG")
                        .HasColumnType("int");

                    b.HasKey("MACC");

                    b.HasIndex("MANV");

                    b.ToTable("CHAMCONG");
                });

            modelBuilder.Entity("QLTL.Models.CHUCVU", b =>
                {
                    b.Property<long>("MACV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MACV"));

                    b.Property<decimal>("LUONG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MACV");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("QLTL.Models.KHENTHUONGKYLUAT", b =>
                {
                    b.Property<long>("MAKHENTHUONGKILUAT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MAKHENTHUONGKILUAT"));

                    b.Property<string>("LYDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MANV")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NGAYAPDUNG")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SOTIEN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("THUONGPHAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAKHENTHUONGKILUAT");

                    b.HasIndex("MANV");

                    b.ToTable("KHENTHUONGKYLUAT");
                });

            modelBuilder.Entity("QLTL.Models.NHANVIEN", b =>
                {
                    b.Property<long>("MANV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MANV"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BIRTHDAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MACV")
                        .HasColumnType("bigint");

                    b.Property<long>("MAPB")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAYVAOLAM")
                        .HasColumnType("datetime2");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THUMBNAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANV");

                    b.HasIndex("MACV");

                    b.HasIndex("MAPB");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("QLTL.Models.PHONGBAN", b =>
                {
                    b.Property<long>("MAPB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MAPB"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAPB");

                    b.ToTable("PHONGBAN");
                });

            modelBuilder.Entity("QLTL.Models.CHAMCONG", b =>
                {
                    b.HasOne("QLTL.Models.NHANVIEN", "NHANVIEN")
                        .WithMany("CHAMCONG")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHANVIEN");
                });

            modelBuilder.Entity("QLTL.Models.KHENTHUONGKYLUAT", b =>
                {
                    b.HasOne("QLTL.Models.NHANVIEN", "NHANVIEN")
                        .WithMany("KHENTHUONGKILUAT")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHANVIEN");
                });

            modelBuilder.Entity("QLTL.Models.NHANVIEN", b =>
                {
                    b.HasOne("QLTL.Models.CHUCVU", "CHUCVU")
                        .WithMany("NHANVIEN")
                        .HasForeignKey("MACV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTL.Models.PHONGBAN", "PHONGBAN")
                        .WithMany("NHANVIEN")
                        .HasForeignKey("MAPB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHUCVU");

                    b.Navigation("PHONGBAN");
                });

            modelBuilder.Entity("QLTL.Models.CHUCVU", b =>
                {
                    b.Navigation("NHANVIEN");
                });

            modelBuilder.Entity("QLTL.Models.NHANVIEN", b =>
                {
                    b.Navigation("CHAMCONG");

                    b.Navigation("KHENTHUONGKILUAT");
                });

            modelBuilder.Entity("QLTL.Models.PHONGBAN", b =>
                {
                    b.Navigation("NHANVIEN");
                });
#pragma warning restore 612, 618
        }
    }
}
